ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }
easy_admin:
    site_name: 'Admin Pass'
    design:
        brand_color: '#2c3e50'
        menu:
            - { entity: 'Client', icon: 'users' }
            - { entity: 'Password', icon: 'key' }
            - { entity: 'Category', icon: 'tags' }
            - { entity: 'User', icon: 'user' }
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: 'Editer', css_class: 'btn btn-primary' }
            - { name: 'delete', icon: 'trash', label: '', css_class: 'btn btn-danger' }
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
            #- AppBundle\Entity\Category
            #- AppBundle\Entity\Client
            #- AppBundle\Entity\Password
            #- AppBundle\Entity\User
        Client:
            class: AppBundle\Entity\Client
            list:
                fields:
                    - id
                    - { property: 'name', label: 'Nom' }
                    - categories
                    - date
            form:
                fields:
                    - name
                    - { property: 'description', type: 'ckeditor', label: 'description' }
                    - categories
        Category:
            class: AppBundle\Entity\Category
            form:
                fields:
                    - name
        Password:
            class: AppBundle\Entity\Password
            list:
                fields:
                    - title
                    - login
                    - password
                    - url
        User:
            class: AppBundle\Entity\User
            list:
                fields:
                    - username
                    - email
                    - lastLogin
                    - enabled
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', label: 'Password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }