wingz_pass_homepage:
    path:     /
    defaults: { _controller: wingzPassBundle:Default:index }

wingz_pass_category:
    path:     /pass
    defaults: { _controller: wingzPassBundle:Clients:index }

# wingz_pass_category_add:
#     path:     /category/add
#     defaults: { _controller: wingzPassBundle:Category:index }
